--- 
# tasks file for install_nginx
#- name: Install NINX
- block:
  - name: Set timezone to Asia/Barnaul
    timezone:
      name: Asia/Barnaul

  - name: Install REPO
    yum_repository:
      name: epel
      description: epel repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no

  - shell: yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm
  - shell: yum-config-manager --enable remi-php72
  
  - name: Install packeg
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - policycoreutils-python
      - nginx
      - php
      - php-fpm
      - php-*
    notify:
      - startup_nginx
      - startup_php-fpm


  - name: 
    firewalld:
      service: "{{ item }}"
      permanent: yes
      state: enabled
    loop:
      - http
      - https

  - name: Allow Apache to listen on tcp port 8888
    seport:
      ports: 8888
      proto: tcp
      setype: http_port_t
      state: present
    notify:
      - restart_nginx

  #- name: Конфигурируем NGINX
  #  template:
  #    src: def_nginx.conf.j2
  #    dest: /etc/nginx/nginx.conf
  #- copy:
  #    src: "{{ item }}"
  #    dest: /etc/nginx/conf.d/
  #  with_fileglob:
  #    - roles/install_nginx/files/{{ conf_file }}
  #- copy:
  #    src:  roles/install_nginx/files/info.php
  #    dest: /usr/share/nginx/html/info.php
  #  notify:
  #    - restart_nginx

  
  when: ansible_os_family == "RedHat"
 